import {
  brandIcon,
  cardImage1,
  cardImage2,
  cardImage3,
  cardImage4,
} from '../images';

export const similarProducts = [
  {
    id: 1,
    image: cardImage1,
    logo: brandIcon,
    description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    sex: 'Men',
    rate: 4,
    rateVotes: 22,
    price: 9999,
    discount: 50,
    size: 'Large',
    pickup: 'Genena Mall',
    from: 'UK',
    to: 'Egypt',
    duration: '10',
    listPrice: 9999,
  },
  {
    id: 2,
    image: cardImage2,
    logo: brandIcon,
    description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    sex: 'Men',
    rate: 4,
    rateVotes: 22,
    price: 9999,
    discount: 0,
    size: 'Large',
    pickup: '',
    from: 'UK',
    to: 'Egypt',
    duration: '10',
    listPrice: 0,
  },
  {
    id: 3,
    image: cardImage3,
    logo: brandIcon,
    description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    sex: 'Men',
    rate: 4,
    rateVotes: 22,
    price: 9999,
    discount: 50,
    size: 'Large',
    pickup: 'Genena Mall',
    from: 'UK',
    to: 'Egypt',
    duration: '10',
    listPrice: 9999,
  },
  {
    id: 4,
    image: cardImage4,
    logo: brandIcon,
    description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    sex: 'Men',
    rate: 4,
    rateVotes: 22,
    price: 9999,
    discount: 50,
    size: 'Large',
    pickup: '',
    from: 'UK',
    to: 'Egypt',
    duration: '10',
    listPrice: 9999,
  },
  {
    id: 5,
    image: cardImage1,
    logo: brandIcon,
    description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    sex: 'Men',
    rate: 4,
    rateVotes: 22,
    price: 9999,
    discount: 30,
    size: 'Large',
    pickup: 'Genena Mall',
    from: 'UK',
    to: 'Egypt',
    duration: '10',
    listPrice: 9999,
  },
  {
    id: 6,
    image: cardImage2,
    logo: brandIcon,
    description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    sex: 'Men',
    rate: 4,
    rateVotes: 22,
    price: 9999,
    discount: 30,
    size: 'Large',
    pickup: 'Genena Mall',
    from: 'UK',
    to: 'Egypt',
    duration: '10',
    listPrice: 9999,
  },
];
